import './globals.css'
import type { Metadata } from 'next'
import {  Montserrat } from 'next/font/google'
import Header from '../components/Header'



export const metadata: Metadata = {
  title: 'Next ecomerce',
  description: 'Generated by create next app',
}

const monsterrat=Montserrat({
  subsets:["latin"],
  display:"swap"
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={monsterrat.className}>
      <body >
        <Header />
        {children}
        </body>
    </html>
  )
}
